version: '3'

services:
  metacubexd:
    container_name: metacubexd
    image: ghcr.io/wy-wy-w/metacubexd
    restart: always
    ports:
      - '80:80'

  # optional
  meta:
    container_name: meta
    image: docker.io/metacubex/mihomo:Alpha
    restart: always
    pid: host
    ipc: host
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./config.yaml:/root/.config/mihomo
